### ISSUE TITLE
How to build this sln?

### ISSUE THREAD

**Issue by matakk** [Xathz/Video-Notifications#1]
With Visual studio 2017?
my 2015 is build falied 

1>G:\sf\youtube\Video-Notifications\Video-Notifications\Constants.cs(38,17,38,19): error CS1043: { or ; expected
1>G:\sf\youtube\Video-Notifications\Video-Notifications\Constants.cs(38,17,38,19): error CS1513: } expected
1>G:\sf\youtube\Video-Notifications\Video-Notifications\Constants.cs(40,10,40,10): error CS1513: } expected
1>G:\sf\youtube\Video-Notifications\Video-Notifications\Forms\FormsManager.cs(27,17,27,19): error CS1043: { or ; expected
1>G:\sf\youtube\Video-Notifications\Video-Notifications\Forms\FormsManager.cs(27,17,27,19): error CS1513: } expected
1>G:\sf\youtube\Video-Notifications\Video-Notifications\Forms\FormsManager.cs(29,10,29,10): error CS1513: } expected
1>G:\sf\youtube\Video-Notifications\Video-Notifications\Forms\SplashForm.cs(36,29,36,31): error CS1002: ; expected

**Comment by Xathz** [comment]
Yea, it builds fine with VS2017. Sadly I can't test on any other version of VS.
Nothing else special is needed beyond [VS2017](https://www.visualstudio.com/vs/community/).
